version: '3.8'

services:
  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - data:/data
    environment:
      - MONGO_INITDB_ROOT_USERNAME=rootuser
      - MONGO_INITDB_ROOT_PASSWORD=rootpass
    networks:
      - giornale-network

  mongo-express:
    image: mongo-express
    container_name: mongo-express
    ports:
      - "8081:8081"
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongodb
      - ME_CONFIG_MONGODB_ADMINUSERNAME=rootuser
      - ME_CONFIG_MONGODB_ADMINPASSWORD=rootpass
    networks:
      - giornale-network

  giornale:
    build: .
    container_name: giornale-app
    restart: on-failure
    ports:
      - "8080:8080"
    depends_on:
      - mongodb
      - mongo-express
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb://rootuser:rootpass@mongodb:27017/giornale?authSource=admin
    networks:
      - giornale-network

volumes:
  data: {}

networks:
  giornale-network:
    driver: bridge

