name: Build & Test

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      mongo:
        image: mongo:6.0
        ports:
          - 27017:27017
        env:
          MONGO_INITDB_ROOT_USERNAME: rootuser
          MONGO_INITDB_ROOT_PASSWORD: rootpass

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Wait for MongoDB to be ready
        run: sleep 20

      - name: Build Project
        run: mvn clean package

      - name: Run Project
        run: mvn install -DskipTests
